### PR TITLE
Add reactive observables to User location

### PR DESCRIPTION
**Pull request by silenium-dev**
I currently require getting all location updates immediately when they arrive, but using a poll thread is obviously not a good solution.
So I got the idea to add RxJava to the plugin to be able to subscribe to any changes without the overhead of polling a player permanently.
**Important:** if you use this API, you must not run any time-consuming operations inside the subscription or use ``observeOn`` to run your code asynchronously in another thread

### CODE REVIEW

**Comment by silenium-dev** [comment]
Maybe the commits should be squashed for cleaner commit history, as one of the two commits is the merge from upstream into my fork.

**Comment by LXGaming** [comment]
Hmm, could this be done without rxjava, seems like a massive library to add for something that could be simply implemented in Java

**Comment by silenium-dev** [comment]
This could be done via manual callbacks, but you'll loose the ability to schedule callbacks in another thread.

**Comment by LXGaming** [comment]
Was going to use the Guava EventBus as that's already present in BungeeCord and Velocity but that has a JavaDoc which advises against using it.

**Comment by silenium-dev** [comment]
Alright, I've added an observable for player join and leave too, going to create a pull request shortly

**Comment by LXGaming** [comment]
Can't you just use the events provided by the platforms (BungeeCord / Velocity), They are what Location uses anyway

**Comment by silenium-dev** [comment]
No, as they are triggered before the player is registered in the plugin's User set

**Comment by LXGaming** [comment]
The event listeners in Location make use of the PostOrder / priority you should be able to schedule your event listeners to be run AFTER Locations

**Comment by silenium-dev** [comment]
Ok, I'll try that

**Comment by silenium-dev** [comment]
Works, thank you

**Comment by LXGaming** [comment]
Awesome, Thanks for the contribution.

Release: https://github.com/LXGaming/Location/releases/tag/v1.4.0

**Comment by silenium-dev** [comment]
Great, I'm just waiting for the maven publish to be able to use it.
Thanks for your time

**Comment by LXGaming** [comment]
Should be available in roughly an hour, Central updates on a schedule.

**Pull request merged**
